name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "eauditrisk.com"
          username: "ubuntu"
          key: ${{ secrets.KEY }}
          script: |
            cd kijani
            git pull
            sudo docker build -t kijani .
            sudo docker stop kijani || true
            sudo docker rm kijani || true
            docker run -d -p 3000:3000 --name kijani kijani
            
